learning_rate: [0.1] 
n_estimators: [100,200] 
max_depth: [5,6,7,8]
min_child_weight: [2,3,4,5,6]
gamma: [0]
subsample: [0.8,0.9,1.0] 
colsample_bytree: [0.8,0.9, 1.0] 
nthread: [-1]
scale_pos_weight: [1] 
seed: [42]